### ISSUE TITLE
Typos in source code

### ISSUE THREAD

**Issue by Kaspik** [baguio/SwiftSafeURL#2]
https://github.com/baguio/SwiftSafeURL/blob/3656ad1146c6255e47d31ab7ddcc4595d29e30fe/Sources/SafeURLLintFramework/SafeURLLintFramework.swift#L8

should be `invalidSafeInputRegexes `? ✌🏼

Also:
https://github.com/baguio/SwiftSafeURL/blob/3656ad1146c6255e47d31ab7ddcc4595d29e30fe/Sources/SafeURLLintFramework/SafeURLLintFramework.swift#L14
should ne `disabledComment`

**Comment by jhonatn** [comment]
You're absolutely correct about the first one. The Duolingo bird is going to be mad for that one. I can fix that in the next commit, unless you want to convert this issue into a PR

But for the second one maybe I'm not using the right words to convey the intention there. That line refers to a comment that can appear in code that disables the analysis being done, therefore, a "disabler comment". Maybe `disablingComment` fits better? What do you think?

**Comment by Kaspik** [comment]
I would do `commentDisabler` if it's an actor. :)

**Comment by mgrider** [comment]
In my opinion, `commentDisabler` makes it sound like it's disabling a comment, as opposed to a comment that disables. My vote would definitely be for `disablingComment`, or maybe `disabledModeComment` to match `warnModeComment` below it.

Other options include `commentToDisable` or `commentThatDisables`, but I think both of those would require renaming `warnModeComment` to match.

**Comment by Kaspik** [comment]
Sure, disablingComments sounds okay too. :)

**Comment by jhonatn** [comment]
Updated at 4de5bb74bd7a765ba9e2b3eb1699d60937aa7654. Thank you for the notes!
