### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by daveverwer** [baguio/SwiftSafeURL#3]
Hello again! I noticed there's no license file included with this repository (and its dependency, too). Is that an oversight?

**Comment by jhonatn** [comment]
It was! I'm sorry for the inconvenience. This is now its solved by 842eedfbec76e73460e943e8a0ea2c6c97754621 and baguio/XcodeIssueReporting@eba927579ff7f32bd09471a0a746f0729954cd04
